### ISSUE TITLE
Menu button

### ISSUE THREAD

**Issue by bheinle7** [W8sconsin/studentlist#10]
If the user clicks the menu button quickly the X sign will show when the menu isn't open or the three bars will show when the menu is open. 
![capture](https://user-images.githubusercontent.com/20329863/27157192-127f6c24-5126-11e7-801d-ab9d7b1882c5.PNG)
![image](https://user-images.githubusercontent.com/20329863/27157209-260d2e66-5126-11e7-9c08-38f568936f59.png)

**Comment by W8sconsin** [comment]
I have a hunch about what is going on here, but I'd be interested in what other people think is going on.  I think we need to insert the css for the menu icon -> x transition into the menu js.  Right now the happen independently.  This will be a good challenge for someone.

**Comment by lestec** [comment]
I have a quick question to clarify to the bug. In bootstrap the 3 line bar usually stays open when clicked on so you are able to click back on it to close the menu. Is there another way we want to close the menu?

**Comment by W8sconsin** [comment]
What we want is the "animated icon" https://www.w3schools.com/howto/howto_css_menu_icon.asp  It works, but double-clicking causes the bug.

**Comment by lestec** [comment]
Thank you for the clarification. : )

**Comment by W8sconsin** [comment]
Rewrote the JS to get this to work.  Check out the changes.
