### ISSUE TITLE
Shadow Effect on Names

### ISSUE THREAD

**Issue by bheinle7** [W8sconsin/studentlist#13]
![image](https://user-images.githubusercontent.com/20329863/27157519-7a595d54-5127-11e7-9822-d87d5dfe610f.png)

**Comment by W8sconsin** [comment]
To elaborate a bit, we are looking for shadow or border for a slightly raised, 3D effect.  It's an idea that Ben and I have been toying with.  Maybe, though, this style should just happen on hover.

**Comment by lestec** [comment]
Hi, I got the shadow effect to work on the names. Here is a screenshot of it:
![shadownames](https://user-images.githubusercontent.com/20157374/27204491-5afad1a4-51e0-11e7-9938-8f015add2a16.png)
Just let me know if its what you wanted, or more shadow?

**Comment by W8sconsin** [comment]
I think that looks great.  I tend to like subtle for shadow effects.

**Comment by bheinle7** [comment]
Awesome!

**Comment by lestec** [comment]
Should I set it up for a pull request? Sorry I'm still new to Git : )
Also do you want me to try to set a hover over effect that when hovered over it appears to make larger, zoom in on each column with the name?

**Comment by W8sconsin** [comment]
@lestec Could you add the shadow effect changes in the newly created dev branch.  Then do a pull request.  I would say no for the hover effect for now, because now that I think about it, when we make the tiles draggable, your changes might be overriden or conflict.

**Comment by W8sconsin** [comment]
Add this shadow effect to the button, used a similar shadow effect in lieu of modal effect on menu.
